custom_section_1:
  type: string
  default: ""
  description:
    en: "Custom navigation menu section to show to specific group.  Group visibilty must be set to all in the group interaction settings."

restrict_section_to_these_groups_only:
  type: list
  list-type: group
  default: ""
  description:
    en: "Restrict user status to these groups only (ie: staff, SuperUsers, Managers)."
