group_menus:
  type: objects
  default: []
  schema:
    name: group_menus
    identifier: menu_name
    properties:
      menu_name:
        type: string
        required: true
        validations:
          min_length: 1
          max_length: 50
      group_id:
        type: groups
        required: true
        validations:
          max: 1

hide_custom_menus_globe_icon:
  type: bool
  default: false
  description:
    en: "Hide the custom menu globe icon from staff (this setting only affects staff, since non-staff cannot see the globe by default)."
