custom_section_1:
  type: string
  default: ""
  description:
    en: "Custom navigation menu section to show to group(s) in setting below. User lowercase slug names."

restrict_section_1_to_these_groups_only:
  type: list
  default: ""
  description:
    en: "Display custom section 1 to these groups only. Group visibilty must be set to Everyone in the group interaction settings."

custom_section_2:
  type: string
  default: ""
  description:
    en: "Custom navigation menu section to show to group(s) in setting below."

restrict_section_2_to_these_groups_only:
  type: list
  default: ""
  description:
    en: "Display custom section 2 to these groups only."

custom_section_3:
  type: string
  default: ""
  description:
    en: "Custom navigation menu section to show to group(s) in setting below."

restrict_section_3_to_these_groups_only:
  type: list
  default: ""
  description:
    en: "Display custom section 3 to these groups only."

custom_section_4:
  type: string
  default: ""
  description:
    en: "Custom navigation menu section to show to group(s) in setting below."

restrict_section_4_to_these_groups_only:
  type: list
  default: ""
  description:
    en: "Display custom section 4 to these groups only."

custom_section_5:
  type: string
  default: ""
  description:
    en: "Custom navigation menu section to show to group(s) in setting below."

restrict_section_5_to_these_groups_only:
  type: list
  default: ""
  description:
    en: "Display custom section 5 to these groups only."
