menu_section_1:
  type: string
  default: ""
  description:
    en: "Navigation menu section 1 to show to group(s) in setting below. User lowercase slug names."

restrict_section_1_to_these_groups_only:
  type: list
  default: ""
  description:
    en: "Display menu section 1 to these groups only. Group visibilty must be set to Everyone in the group interaction settings."

menu_section_2:
  type: string
  default: ""
  description:
    en: "Navigation menu section to show to group(s) in setting below."

restrict_section_2_to_these_groups_only:
  type: list
  default: ""
  description:
    en: "Display menu section 2 for these groups only."

menu_section_3:
  type: string
  default: ""
  description:
    en: "Navigation menu section to show to group(s) in setting below."

restrict_section_3_to_these_groups_only:
  type: list
  default: ""
  description:
    en: "Display menu section 3 for these groups only."

menu_section_4:
  type: string
  default: ""
  description:
    en: "Navigation menu section to show to group(s) in setting below."

restrict_section_4_to_these_groups_only:
  type: list
  default: ""
  description:
    en: "Display menu section 4 for these groups only."

menu_section_5:
  type: string
  default: ""
  description:
    en: "Navigation menu section to show to group(s) in setting below."

restrict_section_5_to_these_groups_only:
  type: list
  default: ""
  description:
    en: "Display menu section 5 for these groups only."
